Replaced deprecated preg_replace /e
symphonists/search_index pull request #55
Opened 2017-04-03 07:51 UTC by animaux

- Replaced deprecated preg_replace /e in lib/class.search_index.php

2017-04-05 21:19 UTC, nitriques commented
Should I wait for #56 tu be pushed and fix as well ?

2017-04-05 21:20 UTC, nitriques requested changes

2017-04-05 21:20 UTC, nitriques commented on lib/class.search_index.php
> +
Could you try to fix the indentation here please ?

2017-04-06 06:12 UTC, animaux commented
@nitriques yes, will try to fix #56 as well. My editor uses spaces not tabs for indentation. I guess that’s waht you like to be fixed?

2017-04-06 14:55 UTC, animaux commented
Indentation should be fixed now.

2017-04-07 16:43 UTC, nitriques commented
> . I guess that’s what you like to get fixed?

Yeah. The best thing is to keep with the original indentation of the file. If it's tabs, continue with tabs, if it's spaces, go with spaces. Which text editor do you use ?

2017-04-07 17:01 UTC, animaux commented
I’m using BBEdit. In my current settings the indentation looked identical to me. Had to switch on invisibles to notice the difference :) Will do the deletion and update the PR on monday. Thanks Nicolas!

2017-04-07 18:52 UTC, nitriques commented
Thanks a lot! You do not need to create a new PR, just push to this one and add Fix #56 in the commit message !

2017-04-07 18:54 UTC, nitriques commented
> Had to switch on invisibles to notice the difference

Yeah I always have that on ;) Sadly BBEdit does not seems to support auto-detection like Sublime does.

2017-04-07 18:54 UTC, nitriques approved these changes

2017-04-10 06:23 UTC, animaux commented
Fixes https://github.com/symphonists/search_index/issues/56.

2017-04-10 06:27 UTC, animaux commented
@nitriques please pull! `:)` or will this be pulled automatically if I close it, since it is approved?

2017-04-10 20:51 UTC, merged

2017-04-10 20:54 UTC, nitriques commented
I've merged in integration first, you might have to flush your local master. out in https://github.com/symphonists/search_index/releases/tag/0.9.5 !

2017-04-10 20:56 UTC, animaux commented
Great, merci!